name = "Create One Block"
author = "Mathiol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ee21e702bb47cbf61a0d688ae1b017e1205ff955ab9700268b243c47be6ec6f"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
