name = "Create One Block"
author = "Mathiol"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af2927fef9a7b2f1070ad2d934daac93f55ca5abd53258357293e4d4a4f2983c"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
