name = "Create One Block"
author = "Mathiol"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6bdc6968e7b11eecef3412b8e870419a83aa2ed0a0b0be8159555b559bf1175"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
